name: Android

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Clone Project
        uses: actions/checkout@v2

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
            java-version: 11

      - name: Run Checks
        run: ./gradlew check --stacktrace

