name: Android CI

on:
  pull_request:
    branches: [ master ]

env:
  API_SERVER_URL: "https://api.github.com/graphql"
  API_ACCESS_TOKEN: "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"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v2

      - name: Local Properties
        run: |
          echo API_SERVER_URL=${API_SERVER_URL} >> local.properties
          echo API_ACCESS_TOKEN=${API_ACCESS_TOKEN} >> local.properties
          cat local.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Lint
        run: ./gradlew lint

      - name: Upload Lint Report
        uses: actions/upload-artifact@v2
        with:
          name: lint.html
          path: app/build/reports/lint-results-debug.html

  unit-test:
    needs: [ lint ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v2

      - name: Local Properties
        run: |
          echo API_SERVER_URL=${API_SERVER_URL} >> local.properties
          echo API_ACCESS_TOKEN=${API_ACCESS_TOKEN} >> local.properties
          cat local.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Tests
        run: ./gradlew test

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/

  instrumentation-test:
    needs: [ unit-test ]
    runs-on: macos-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@v2

      - name: Local Properties
        run: |
          echo API_SERVER_URL=${API_SERVER_URL} >> local.properties
          echo API_ACCESS_TOKEN=${API_ACCESS_TOKEN} >> local.properties
          cat local.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Run Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: instrumentation_test_report
          path: app/build/reports/androidTests/connected/

  build:
    name: Generate APK
    needs: [ instrumentation-test ]
    runs-on: ubuntu-latest
    steps:

      - name: Clone Project
        uses: actions/checkout@v2

      - name: Local Properties
        run: |
          echo API_SERVER_URL=${API_SERVER_URL} >> local.properties
          echo API_ACCESS_TOKEN=${API_ACCESS_TOKEN} >> local.properties
          cat local.properties

      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build Debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: github-projects.apk
          path: app/build/outputs/apk/debug/app-debug.apk

